kettanaito/atomic-layout

- src/Layout.js
- src/const/defaultOptions.js
- src/utils/applyStyles.js
- src/utils/getAreaParams.js
- src/utils/getAreaParams.spec.js
- src/utils/getAreasList.js
- src/utils/getComponents.js
- src/utils/invariant.js
- src/utils/math/calc.js
- src/utils/math/calc.spec.js
- src/utils/math/parseNumeric.js
- src/utils/math/parseNumeric.spec.js
- src/utils/parsePropName.js
- src/utils/parsePropName.spec.js
- src/utils/toNumber.js
- src/utils/toNumber.spec.js
> Handles string breakpoint values

- examples/behavior/Bell.jsx
- examples/behavior/Inclusive.jsx
- examples/behavior/MobileFirst.jsx
- examples/composition/NestedComposition.jsx
- examples/responsive-props/BreakpointSpecific.jsx
- examples/responsive-props/CustomConfiguration.jsx
- examples/responsive-props/InclusiveBell.jsx
- examples/responsive-props/MobileFirst.jsx
- examples/webpack.config.js
- src/utils/getAreaParams/getAreaParams.js
- src/utils/getAreaParams/getAreaParams.spec.js
- src/utils/getAreasList/getAreasList.spec.js
- src/utils/getComponents/getComponents.js
- stories/index.js
> (Optional) Please list the issues related or covered by this pull request. Otherwise remove this section.
* Fixes #21 
> Please list the current or upcoming changes introduced by this pull request. In case of intermediate pull request, mark the finished changes so the roadmap is evident.
> Verifies "down" area behavior

- src/components/Composition.jsx
- src/utils/createMediaQuery/createMediaQuery.js
- src/utils/generateComponents/generateComponents.js
- src/utils/generateComponents/index.js
- src/utils/getAreaParams/getAreaParams.spec.js
- src/utils/getComponents/index.js
- src/utils/parseTemplates/parseTemplates.js
- src/utils/pick/pick.js
> Please list the current or upcoming changes introduced by this pull request. In case of intermediate pull request, mark the finished changes so the roadmap is evident. 
- Renames `getComponents` to `generateComponents` to be more descriptive
- Provides JSDocs description for `generateComponents`
> Improves function names

- .circleci/config.yml
> (Optional) Please list the issues related or covered by this pull request. Otherwise remove this section.
* Fixes #43
> Please list the current or upcoming changes introduced by this pull request. In case of intermediate pull request, mark the finished changes so the roadmap is evident. 
- Performs bundle size check right after the library build
> CircleCI: Performs bundle size check immediately after library build

- package-lock.json
- src/Layout.spec.js
- src/utils/templates/getAreasList/getAreasList.js
* #40  Increases test coverage
* Removes unnecessary condition
> Increase test coverage

- package-lock.json
- package.json
> (Optional) Please list the issues related or covered by this pull request. Otherwise remove this section.
* Fixes #49 
> Please list the current or upcoming changes introduced by this pull request. In case of intermediate pull request, mark the finished changes so the roadmap is evident. 
- Adds "lint-staged" package as dev dependency
- Performs eslint, prettier and `git add` commands on `precommit` hook
- Adjusts npm scripts in `package.json`
> Adds "lint-staged"

- cypress/integration/index.js
- cypress/integration/prop-aliases/index.js
- cypress/support/commands.js
- examples/Root.jsx
- examples/misc/PropAliases.jsx
- examples/misc/index.jsx
- package.json
> (Optional) Please list the issues related or covered by this pull request. Otherwise remove this section.
* Fixes #52 
> Please list the current or upcoming changes introduced by this pull request. In case of intermediate pull request, mark the finished changes so the roadmap is evident. 
- Adds integration test for assuring that prop aliases are assigned properly on the layout components
- Adds a dedicated route in the examples app
> Adds integration test for prop aliases

- .gitignore
- cypress/integration/bugfixes/index.js
- cypress/integration/bugfixes/template-indentation.test.js
- cypress/integration/index.js
- examples/Root.jsx
- examples/bugfixes/TemplateIndentation.jsx
- examples/bugfixes/index.jsx
- jest.config.js
- src/utils/strings/sanitizeTemplateString/sanitizeTemplateString.js
- src/utils/strings/sanitizeTemplateString/sanitizeTemplateString.spec.js
- Replaces new lines with spaces, instead of empty strings
- Replaces single quotes with spaces
- Deduplicates the spaces
* Closes #65
> Makes template indentation optional

- src/Layout.js
- src/components/Box.jsx
- src/components/Composition.jsx
- src/const/defaultOptions.js
- src/const/propAliases.js
- src/utils/breakpoints/getAreaBreakpoints/getAreaBreakpoints.js
- src/utils/breakpoints/getAreaBreakpoints/getAreaBreakpoints.spec.js
- src/utils/breakpoints/mergeBreakpoints/mergeBreakpoints.js
- src/utils/breakpoints/openBreakpoint/openBreakpoint.js
- src/utils/breakpoints/shouldMergeBreakpoints/shouldMergeBreakpoints.js
- src/utils/functions/compose/compose.js
- src/utils/functions/spread/spread.js
- src/utils/functions/when/when.js
- src/utils/invariant/invariant.js
- src/utils/strings/parsePropName/parsePropName.js
- src/utils/strings/parsePropName/parsePropName.spec.js
- src/utils/strings/sanitizeTemplateArea/sanitizeTemplateArea.js
- src/utils/styles/applyStyles/applyStyles.js
- src/utils/styles/createMediaQuery/createMediaQuery.js
- src/utils/templates/generateAreasList/generateAreasList.js
- src/utils/templates/generateAreasList/generateAreasList.spec.js
- src/utils/templates/generateAreasList/index.js
- src/utils/templates/generateComponents/generateComponents.js
- src/utils/templates/getAreasList/index.js
- src/utils/templates/parseTemplates/filterTemplateProps.js
- src/utils/templates/parseTemplates/parseTemplates.js
The purpose of this pull request is to polish the existing functionality and add the todo blocks of improvement points.
See commit names for change log.
> Adds minor adjustments

- cypress/integration/composition/index.js
- cypress/integration/composition/templateless.test.js
- examples/composition/Templateless.jsx
- examples/composition/index.jsx
- src/components/Composition.jsx
- src/utils/breakpoints/shouldMergeBreakpoints/shouldMergeBreakpoints.js
- stories/Square.jsx
> Adjustments

- package.json
> Removes "postinstall" hook

- cypress/integration/bugfixes/index.js
- cypress/integration/bugfixes/styles-undefined.test.js
- examples/bugfixes/StylesUndefined.jsx
- examples/bugfixes/index.jsx
- src/utils/styles/applyStyles/applyStyles.js
> applyStyles: Rejects props without a value

- .eslintrc
- package.json
- src/components/Composition.jsx
- src/utils/breakpoints/getAreaBreakpoints/getAreaBreakpoints.js
- src/utils/breakpoints/getAreaBreakpoints/getAreaBreakpoints.spec.js
- src/utils/functions/memoizeWith/index.js
- src/utils/functions/memoizeWith/memoizeWith.js
- src/utils/functions/memoizeWith/memoizeWith.spec.js
- src/utils/strings/sanitizeTemplateString/sanitizeTemplateString.js
- src/utils/strings/sanitizeTemplateString/sanitizeTemplateString.spec.js
- src/utils/templates/generateAreasList/index.js
- src/utils/templates/generateComponents/generateComponents.js
- src/utils/templates/getAreasList/getAreasList.js
- src/utils/templates/getAreasList/getAreasList.spec.js
- src/utils/templates/getAreasList/index.js
- src/utils/templates/parseTemplates/filterTemplateProps.js
- src/utils/templates/parseTemplates/filterTemplateProps.spec.js
- src/utils/templates/parseTemplates/parseTemplates.js
- stories/PeriodExample.jsx
- stories/Playground/index.jsx
- webpack.config.js
- yarn.lock
* Proxies the generated components Object to allow dynamic Object key reference, and prevent React exceptions on rendering undefined components.
* Gives developer-friendly warning on development environment when trying to render an undefined template area
* Supports dynamic templates
- Closes #78 
- Closes #85
> Supports components Proxy

- cypress/integration/only/custom.spec.js
- cypress/integration/only/default.spec.js
- cypress/integration/only/index.js
- examples/only/OnlyCustom.jsx
- examples/only/index.jsx
- src/components/Only.tsx
- src/utils/templates/generateComponents/generateComponents.tsx
> Only: Supports custom breakpoint objects

- package.json
> fix 107 incorrect peer dependencies

- cypress/integration/other/prop-aliases.spec.js
- examples/behavior/Inclusive.jsx
- examples/behavior/MobileFirst.jsx
- examples/behavior/Notch.jsx
- examples/bugfixes/TemplateIndentation.jsx
- examples/custom-configuration/CustomBreakpoints.jsx
- examples/other/PolymorphicProp.jsx
- examples/other/PropAliases.jsx
- examples/responsive-props/BreakpointSpecific.jsx
- examples/responsive-props/InclusiveNotch.jsx
- examples/responsive-props/MobileFirst.jsx
- src/const/propAliases.ts
- src/utils/templates/parseTemplates/filterTemplateProps.ts
- stories/Demo.jsx
- stories/PeriodExample.jsx
Adds the `areas` prop alias for `grid-template-areas`.
- Closes #121
> Adds "areas" prop alias

- src/utils/breakpoints/mergeBreakpoints/mergeBreakpoints.spec.ts
- src/utils/breakpoints/mergeBreakpoints/mergeBreakpoints.ts
- Adds unit test for `mergeBreakpoints` util
- Closes #155
> Adds unit test for "mergeBreakpoints" util

- cypress/asserts/assertBell.js
- cypress/integration/composition/nested-composition.test.js
- cypress/integration/hooks/index.js
- cypress/integration/hooks/useResponsiveProps.spec.js
- cypress/integration/rendering/bell.test.js
- cypress/integration/rendering/inclusive.test.js
- cypress/integration/rendering/index.js
- cypress/integration/responsive-props/bell-notch.test.js
- cypress/integration/responsive-props/index.js
- examples/Components/Composition/NestedComposition.jsx
- examples/Core/Rendering/Bell.jsx
- examples/Hooks/UseResponsiveProps.jsx
- examples/index.js
- package.json
- src/hooks/useResponsiveProps.ts
- src/index.ts
- Adds `useResponsiveProps` hook that makes any given props responsive
- Closes #148
> Adds "useResponsiveProps" hook

- cypress/integration/recipes/grid-template.spec.js
- examples/Components/Only/OnlyCustomBreakpoint.jsx
- examples/Hooks/UseViewportChange.jsx
- src/const/defaultOptions.ts
- Adjusted breakpoints defaultOptions to match Bootstrap grid
- Closes #204
> Fix default breakpoints to match bootstrap grid

- rollup.config.js
- Rollup - ESM build - Fix babel plugins
- Rollup - UMD build - Fix babel plugins
- Closes #206
> Rollup - ESM UMD builds - Fix babel plugins

- README.md
- Adds "Examples" section to README. It will serve as the list of most useful examples for beginners and whatnot.
> Adds "Examples" section to the README

- examples/Square.jsx
- examples/components/Composition/declaration/GridTemplate.jsx
- examples/components/Composition/declaration/GridTemplate.test.js
- Adds missing integration test scenario that asserts the "auto" as a value of the `grid-template` CSS property.
- Closes #215
> Adds integration test scenario to assert "auto" grid-template values

- .storybook/webpack.config.js
- examples/Hooks/UseResponsiveComponent.jsx
- examples/all.test.js
- examples/hooks/UseResponsiveComponent.jsx
- examples/hooks/useResponsiveComponent.test.js
- examples/index.js
- package.json
- src/hooks/useBreakpointChange.ts
- src/hooks/useResponsiveComponent.tsx
- src/hooks/useResponsiveProps.ts
- src/hooks/useResponsiveValue.ts
- src/index.ts
- tslint.json
- yarn.lock
> Mirror of #213 that includes proper "examples" directories casing.
- Adds a new `useResponsiveComponent` hook to be a shorthand for `useResponsiveProps` + React component declaration
- Linting: Allows [object literal type assertions](https://palantir.github.io/tslint/rules/no-object-literal-type-assertion/)
- Closes #194
> Hooks: Adds "useResponsiveComponent" hook

- .github/PULL_REQUEST_TEMPLATE.md
- Pull request template now has section headings of level 2 (h2)
- Slightly changes the wording of  `Change log` -> `Changes`
- Closes #221
> Sets Pull request template headings to have level 2

- src/Layout.spec.ts
- src/Layout.ts
- src/const/propAliases.spec.tsx
- src/hooks/useResponsiveComponent.tsx
- src/hooks/useResponsiveProps.ts
- src/utils/breakpoints/closeBreakpoint/closeBreakpoint.ts
- src/utils/breakpoints/getAreaRecords/getAreaRecords.ts
- src/utils/functions/pop/pop.spec.ts
- src/utils/functions/throttle/throttle.spec.ts
- src/utils/functions/throttle/throttle.ts
- src/utils/functions/warn/warn.spec.ts
- src/utils/strings/parsePropName/parsePropName.ts
- src/utils/strings/sanitizeTemplateArea/sanitizeTemplateArea.ts
- src/utils/styles/applyStyles/applyStyles.ts
- src/utils/templates/generateComponents/generateComponents.tsx
- tsconfig.json
- Sets `noImplicitAny: true` in the `tsconfig.json`
- Fixes the source code not to contain any implicit any
- Fixes `propAliases.spec` test to assert each value in a values set
> Improves type definitions, forbids implicit any

- src/index.ts
- The default options object is now exported for more comfortable custom options composition (i.e. to extend default breakpoints with a custom one without explicitly repeating all the defaults)
No related issue.
> Exports the default options

- package.json
- Adds the new "funding" key in `package.json`. When present, it will notify the consumers that Atomic Layout supports public funding through Open Collective, and include the donation URL during the installation process.
> Adds the "funding" setting to NPM

- examples/components/Visible/Visible.test.js
- examples/components/Visible/VisibleDefaultBehavior.jsx
- src/components/Visible.tsx
- Conditionally sets `aria-hidden="true"` attribute on the `Visible` component when it should hide the contents
- Closes #252
> Visible: Sets "aria-hidden" for visually hidden component

- .github/PULL_REQUEST_TEMPLATE.md
- package.json
- Adds `yarn ci` command for fast healthcheck
- Improves the Pull request template to include release version, contributor's checklist
- Relates to #258
> Adds "yarn ci" command

- .storybook/config.js
- examples/all.test.js
- examples/components/Only/OnlyDefaultBehavior.test.js
- examples/components/Visible/Visible.test.js
- examples/components/Visible/VisibleDefaultBehavior.jsx
- examples/index.js
- src/components/MediaQuery.tsx
- src/components/Only.tsx
- src/components/Visible.tsx
- src/hooks/useMediaQuery.ts
- src/index.ts
> Release: 0.11.0

- packages/atomic-layout-core/package.json
- packages/atomic-layout/package.json
fixed the broken repository links in package.json
- Closes #266
> fix broken repository links in package.json

- packages/atomic-layout-core/rollup.config.js
When attempting to use `atomic-layout@0.12.2` in a NextJS project encountered the next exception:
```
/Users/kettanaito/Projects/.../node_modules/@atomic-layout/core/lib/index.js:870
export { Layout$1 as Layout, applyStyles, flipBreakpoint as closeBreakpoint, compose, createMediaQuery, defaultOptions, generateComponents, joinQueryList, mergeAreaRecords, normalizeQuery, openBreakpoint, parsePropName, parseTemplates, propAliases, throttle, transformNumeric, warn, withBreakpoints };
^^^^^^
SyntaxError: Unexpected token export
at Module._compile (internal/modules/cjs/loader.js:723:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load …
```
> Builds @atomic-layout/core into cjs module

- packages/atomic-layout/examples/all.test.js
- packages/atomic-layout/examples/index.js
- packages/atomic-layout/examples/regression/SingleResponsiveProp.jsx
- packages/atomic-layout/examples/regression/SingleResponsiveProp.test.js
- Adds missing E2E tests to ensure single responsive props behavior
- Closes #270 
> Adds tests, no release needed.
> Adds E2E tests for single responsive prop

- packages/atomic-layout-core/README.md
- Adds description to the `@atomic-layout/core` package
- Closes #290 
Internal update, no release required.
> @atomic-layout/core: Adds package description

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- Updates the `CONTRIBUTING.md` guidelines to describe the newly introduced monorepo structure for newcomers
- Updates the Pull request template according to the changes I keep doing all the time
- Updates the Bug report template to describe an issue in a more common manner (current/expected)
- Closes #274 
> No release necessary, internal update.
> Updates contributing guidelines to have a monorepo section

- README.md
- packages/atomic-layout-emotion/README.md
- packages/atomic-layout/README.md
> Removes Spectrum badge from README
