cypress/support/commands.js
src/utils/templates/generateComponents/generateComponents.js
stories/Playground/index.jsx

- Sets `display` to `flex` for area components by default
- Sets `display` to `flex` when passed `inline` prop to area component
* Closes #61

Displays generated area components as flexbox

---

cypress/integration/index.js
cypress/integration/only/index.js
cypress/integration/other/polymorphic-prop.spec.js
examples/only/OnlyExample.jsx
examples/only/index.jsx
src/components/Only.tsx
src/utils/templates/generateComponents/generateComponents.tsx
stories/OnlyDemo.jsx
stories/index.js

- Closes #74 
- Provides stable API for inclusive and notch behaviors of Only children
- Reuses the responsive wrapping logic from `generateComponents()`
- Covers Only components with integration tests

Only: Adds support for inclusive and notch behavior

---

.circleci/config.yml
package.json
src/utils/strings/hashString/hasString.spec.ts
src/utils/strings/hashString/hashString.ts
src/utils/strings/hashString/index.ts
src/utils/templates/parseTemplates/parseTemplates.ts
tslint.json

Replaces the call to the browser `btoa`, which doesn't exist on server-side, to prevent it from breaking app's SSR logic.
- Fixes #101

Replace "btoa" call with "hasString" util

---

src/utils/templates/generateComponents/generateComponents.tsx

Removes the reference to the `window` to prevent exceptions during application's SSR.
- Relates to #101

Removes reference to the "window"

---

jest.config.js
src/components/Only.tsx
tests/ssr.spec.tsx

* Adds a simple unit test to assert that server-side rendering doesn't throw an exception when rendering components from `atomic-layout` package.
- Partially covers #72

Adds unit test for SSR

---

cypress/integration/other/prop-aliases.spec.js
src/utils/functions/isset/index.ts
src/utils/functions/isset/isset.spec.ts
src/utils/functions/isset/isset.ts
src/utils/math/transformNumeric.spec.ts
src/utils/math/transformNumeric.ts
src/utils/styles/applyStyles/applyStyles.ts
stories/Demo.jsx

transformNumeric: Handle "0" as the explicit value

---

cypress/integration/other/polymorphic-prop.spec.js
examples/Core/Rendering/PolymorphicProp.jsx
src/components/Box.tsx
src/components/Composition.tsx

- Sets layout-related styles generated by the library's component primitives as the highest priority
- Adds integration tests to ensure proper styles specificity when using polymorphic prop API from `styled-components`
- Closes #150

Ensures style overrides for polymorphic usage

---

src/const/propAliases.spec.tsx
src/const/propAliases.ts
src/const/props.ts
src/utils/breakpoints/getAreaBreakpoints/behaviorUp.spec.ts

- Adds `gap`, `gapCol`, `gapRow` prop alias for `grid-gap`, `grid-column-gap` and `grid-row-gap` correspondingly

Adds "gap" prop alias

---

src/Layout.spec.ts
src/Layout.ts
src/utils/math/transformNumeric.ts
src/utils/strings/parsePropName/parsePropName.ts
src/utils/styles/applyStyles/applyStyles.ts

- Moves Layout options from the dedicated `options` key to the root level of the Layout class
- Adjusts usage surface of `Layout` instance
- Closes #153

Layout: Stores options on the rool level of a class

---

package.json

- Removes `yarn bundlesize` from `prepush` hook
- Leaving `yarn bundlesize` on `prepublishOnly` hook, because it performs `yarn build` before doing the size check
- Closes #161

Removes bundle size check from "prepush" hook

---

cypress/integration/recipes/grid-template.spec.js
cypress/integration/recipes/index.js
examples/Recipes/GridTemplate.jsx
examples/index.js
src/const/propAliases.ts
src/const/props.ts
src/utils/strings/isAreaName/index.ts
src/utils/strings/isAreaName/isAreaName.spec.ts
src/utils/strings/isAreaName/isAreaName.ts
src/utils/strings/sanitizeTemplateArea/sanitizeTemplateArea.spec.ts
src/utils/strings/sanitizeTemplateArea/sanitizeTemplateArea.ts
src/utils/strings/sanitizeTemplateString/sanitizeTemplateString.spec.ts
src/utils/strings/sanitizeTemplateString/sanitizeTemplateString.ts
src/utils/strings/toDashedString/toDashedString.ts

- Extends CSS Grid area string parsing to support `grid-template` definition
- Introduces new `isAreaName` util that asserts a given string as a valid area name (takes into account dimensional values of row/column and keywords)
- Provides respective unit and end-to-end tests
- Provides usage example
- Closes #113 
There are two actions Atomic layout performs with the given `grid-template-areas` (after this pull request with `grid-template` as well):
* Assigns the given value as the value of `grid-template-areas` CSS property
* Extracts CSS Grid areas names from the string
The second one required adjustment in order to support `grid-template` syntax. That syntax allows to specify rows/columns sizes within the grid template string. Internal logic should account for that:
1. Ignoring …

Adds support for "grid-template" prop

---

src/Layout.ts

- Provides explicit check for `options` during instantiating a new `Layout` class
- Fixes an issue that resulted into "missing options" error being thrown by default
- Fixes #173 
> I will ship a succeeding pull request to improve uni test coverage on `Layout` class to improve its sustainability to changes.

Layout: Calls "configure" only when options are provided

---

src/Layout.spec.ts
src/Layout.ts
src/components/Composition.tsx
src/utils/functions/warn/index.ts
src/utils/functions/warn/warn.spec.ts
src/utils/functions/warn/warn.ts
src/utils/invariant/invariant.spec.ts
src/utils/invariant/invariant.ts

- Adds `warn` util
- Throws error instead of `console.error` in `invariant`
- Improves unit tests for `Layout` class
- Closes #177
- Relates to #173

Improves Layout test coverage

---

src/Layout.spec.ts
src/Layout.ts
src/components/Only.tsx
src/utils/breakpoints/getAreaBreakpoints/getAreaBreakpoints.spec.ts
src/utils/strings/parsePropName/parsePropName.ts
src/utils/styles/applyStyles/applyStyles.ts
src/utils/templates/getAreasList/getAreasList.spec.ts
src/utils/templates/getAreasList/getAreasList.ts

- Removes `Layout.getBreakpoint()` and `Layout.getBreakpointNames()` methods in favor of native `Layout.breakpoints[breakpointName]` and `Object.keys(Layout.breakpoints`:
```diff
- Layout.getBreakpoint('md')
+ Layout.breakpoints.md
- Layout.getBreakpointsNames()
+ Object.keys(Layout.breakpoints)
```
- Adjusts internal usage of the removed methods
- No particular issue

Layout: Removes "getBreakpoint" and "getBreakpointNames" methods

---

examples/Hooks/UseResponsiveProps.jsx
src/hooks/useBreakpointChange.ts
src/hooks/useViewportChange.ts

- Fixes issue where custom `debounceDuration` wasn't propagated to the underlying `useViewportChange` hook in `useBreakpointChange` hook
- Sets default debounce duration of `useViewportChange` to `50ms` to improve re-render speed upon viewport changes
- Closes #167

useViewportChange: Sets faster default debounce duration

---

.circleci/config.yml
webpack.config.js

- Splits a single "build" job in CircleCI config to be granular
- Configures custom "release" workflow, specifying certain steps as sequential, and certain as parallel
- Improves the speed of the CI
- Sets `cache: true` and `bail: true` in webpack configuration to cache builds and fail fast on errors
- Closes #180

CI: Parallelizes jobs

---

cypress/integration/composition/index.js
cypress/integration/composition/namespace.test.js
examples/Components/Composition/Namespace.jsx
examples/index.js
src/utils/templates/generateComponents/generateComponents.tsx
tslint.json

Addresses a namespace collision issue between own React components and those areas components generated by the library.
- Introduces a designated `Areas` namespace that holds all the generated area components
- Closes #154

Introduces "Areas" grouped area component

---

.storybook/webpack.config.js
cypress/integration/composition/index.js
cypress/integration/composition/weak-area.test.js
examples/Components/Composition/WeakArea.jsx
examples/index.js
rollup.config.js

- Replaces `__PROD__` environmental variable with the actual value depending on the build
- Adds integration scenario for weak and non-existing areas rendering (Composition)
- Improves debugging of Storybook builds
- Closes #199

ESM: Provides "__PROD__" environmental variable

---

cypress/integration/bugfixes/box-display-override.test.js
cypress/integration/bugfixes/index.js
cypress/integration/other/polymorphic-prop.spec.js
examples/Bugfixes/BoxDisplayOverride.jsx
examples/Bugfixes/TemplateIndentation.jsx
examples/Core/Configuration/CustomBreakpoints.jsx
examples/Core/Rendering/PolymorphicProp.jsx
examples/index.js
src/components/Box.spec.tsx
src/components/Box.tsx

- Moves `display` CSS property assignment in the Box component to the root level of a styled component (previously wrapped in a prioritizing `&&`)
- Adds missing end-to-end test that ensures that Box's `display` can be overridden by the same CSS property of a custom styled component
- Closes #202

Box: Assigns "display" property aside from priority styles

---

src/const/propAliases.spec.tsx
src/const/propAliases.ts

- Adds missing `alignContent` prop alias to the aliases map
- Closes #217

Adds missing "alignContent" prop alias to the aliases map

---

src/hooks/useViewportChange.ts

- stores handler as Ref to prevent recreation.
- Closes #229

stores handleWindowResize with useRef

---

src/hooks/useViewportChange.ts

I'm destructuring current from handleWindowResize ref 
- Closes #232

Fix ref usage at useViewportChange cleanup

---

src/components/Box.tsx
src/components/Composition.tsx
src/components/MediaQuery.tsx
src/components/Only.tsx
src/const/props.ts
src/hooks/useResponsiveComponent.tsx
src/utils/templates/generateComponents/generateComponents.tsx

- `Only` component types now extend `BoxProps` instead of `GenericProps`. This allows for `Only` to have Box props like `flex` and `inline` plus all the generic props.
- Closes #246

Only: Extends "BoxProps" instead of "GenericProps"

---

.storybook/config.js
examples/all.test.js
examples/components/Only/OnlyDefaultBehavior.test.js
examples/components/Visible/Visible.test.js
examples/components/Visible/VisibleDefaultBehavior.jsx
examples/index.js
src/components/MediaQuery.tsx
src/components/Only.tsx
src/components/Visible.tsx
src/hooks/useMediaQuery.ts
src/index.ts

`Visible` component behaves similar to `Only`, but instead of conditional rendering it provides conditional display of its children. Useful for SSR scenarios of dynamically present content, since `Visible` preserves the space taken by an element. Uses `visibility` CSS property to preserve the physical space occupied by the children.
- `MediaQuery` component now respects the initial `matches` value
- Adds `useMediaQuery` hook to resolve to a `boolean` upon a media query match
- `MediaQuery` component now uses `useMediaQuery` hook
- Closes #134

Adds "Visible" component

---

src/hooks/useMediaQuery.ts

Refactors how `useMediaQuery` works so there is no stuttering during re-renders with the same media query state.
- Uses `useLayoutEffect` instead of `useEffect` in `useMediaQuery` hook (synchronously re-renders by awaiting the DOM, meaning, `matchMedia`)
- Closes #234

useMediaQuery: Uses "useLayoutEffect" instead of "useEffect"

---

packages/atomic-layout/examples/hooks/UseResponsiveComponent.jsx
packages/atomic-layout/examples/hooks/useResponsiveComponent.test.js
packages/atomic-layout/src/hooks/useResponsiveComponent.tsx

- Uses `React.forwardRef()` in `useResponsiveComponent` to propagate custom refs set by the user
- Closes #263 
> Although adoption of `React.forwardRef` is a breaking change, I wouldn't release `1.0` due to that. Current state of the library implies experimental API, in terms that it may change or get deprecated even in minor releases. Once the major version is released it will be followed according to semver.

useResponsiveComponent: Uses "React.forwardRef" to propagate ref

---

packages/atomic-layout/examples/hooks/UseResponsiveComponent.jsx
packages/atomic-layout/examples/hooks/useResponsiveComponent.test.js
packages/atomic-layout/src/hooks/useResponsiveProps.ts
packages/atomic-layout/src/hooks/useResponsiveValue.ts

- Adds `useEffect` to resolve next responsive props on input change
- Rewrites `useBreakpointChange` hook in `useResponsiveProps` to derive a state variable that holds the current breakpoint name
- Renames the state setter function in `useResponsiveValue` to `setValue`
- Closes #265

useResponsiveProps: Resolves next props on props change

---

packages/atomic-layout-core/src/index.ts
packages/atomic-layout/package.json
packages/atomic-layout/src/hooks/useResponsiveComponent.spec.tsx
packages/atomic-layout/src/hooks/useResponsiveProps.ts
packages/atomic-layout/tslint.json

- Assigns proper initial value for the state in `useResponsiveProps`
When rendered on a server no React hooks are run. The `useEffect` hook in `useResponsiveProps` is no exception, and this results into server-side markup containing no props at all, because the initial state of the respective `useState` hook is undefined. To prevent this, I make the filtering function parametric and call it with a server-side-like matcher as the initial value of the `useState` hook.
- Adds a unit test for `useResponsiveComponent` function
- Closes #272

useResponsiveProps: Fixes default breakpoint prop value assignment

---

packages/atomic-layout-core/src/utils/strings/isAreaName/isAreaName.spec.ts
packages/atomic-layout-core/src/utils/strings/isAreaName/isAreaName.ts
packages/atomic-layout-core/src/utils/strings/sanitizeTemplateArea/sanitizeTemplateArea.spec.ts
packages/atomic-layout-core/src/utils/strings/sanitizeTemplateArea/sanitizeTemplateArea.ts
packages/atomic-layout-core/src/utils/strings/sanitizeTemplateString/sanitizeTemplateString.spec.ts
packages/atomic-layout-core/src/utils/strings/sanitizeTemplateString/sanitizeTemplateString.ts

- `isAreaName` now accepts an optional `tolerateDots` parameter to control whether a dot symbol must be considered an area name
- Adds unit tests that cover a proper dot placeholder handling
There are two functions that use `isAreaName`, but they use it for different purpose:
- `sanitizeTemplateArea` puts all areas in single quotes and all non-areas array members into dimensional suffixes that follow after the areas were wrapped in single quotes. That is to have a valid `grid-template` syntax:
```css
.composition {
grid-template: 
/* Note that row's dimension is outside of single quotes */
'first . second' 150px
}
```
- `sanitizeTemplateString` accepts a list of area names and returns a list where all members should be converted into React components. That's where the issue originates, as …

Does not generate React component for a dot placeholder

---

packages/atomic-layout/src/hooks/useMediaQuery.ts

- Conditionally decides which hook to use (`useEffect`/`useLayoutEffect`) depending on the environment: `useEffect` is used on the server, `useLayoutEffect` on the client (see #254)
- Closes #293

useMediaQuery: Uses "useEffect" on the server

---

packages/atomic-layout-core/src/const/propAliases.ts
packages/atomic-layout-core/src/const/props.ts
packages/atomic-layout/examples/all.test.js
packages/atomic-layout/examples/components/Composition/declaration/OrderProp.jsx
packages/atomic-layout/examples/components/Composition/declaration/OrderProp.test.js
packages/atomic-layout/examples/index.js

- Adds `order` CSS property support to `GenericProps` interface to be used on `Box` and Composition's areas components
- Closes #295

Adds "order" CSS property support 

---

examples/index.js
examples/regression/DisplayNames.jsx
examples/regression/DisplayNames.test.js
packages/atomic-layout-core/src/utils/templates/generateComponents/generateComponents.ts
packages/atomic-layout/src/components/Box.tsx
packages/atomic-layout/src/components/Composition.tsx
packages/atomic-layout/src/components/MediaQuery.tsx
packages/atomic-layout/src/components/Only.tsx
packages/atomic-layout/src/components/Visible.tsx

- The following exported components are being given a meaningful `displayName` property that mirror the respective component's name:
- `Box`
- `Composition`
- `Visible`
- `Only`
- `MediaQuery`
- Closes #306

Adds meaningful "displayName" to exported components

---

packages/atomic-layout-core/src/utils/strings/parsePropName/parsePropName.spec.ts
packages/atomic-layout-core/src/utils/strings/parsePropName/parsePropName.ts

- Removes the `i` regular expression flag from `parsePropName()`
- Adds unit tests to check that `parsePropName()` does not tolerate breakpoint and/or behavior written in lowercase
- Closes #296 
> Treating this as a minor change, because it introduces a behavior change that is not backward-compatible. Developers who had wrong responsive props declarations (and those still worked due to the previously case-insensitive parsing) will have their responsive broken with this change, and would have to rewrite responsive props to follow proper casing.

Parses prop names in case-sensitive manner

---

examples/index.js
examples/regression/DisplayNames.jsx
examples/regression/DisplayNames.test.js
examples/regression/ParentRerendering.jsx
examples/regression/ParentRerendering.test.js
packages/atomic-layout/src/components/Composition.tsx

- Wraps `generateComponents()` call in `Composition` in `useMemo` hook, so that generated area components do not lose their state whenever parent updates. Change of the value of `areas`/`template` prop would still trigger re-generation of components.
- Removes the assertion on `MediaQuery` from the E2E tests
- Fixes #320

Memoizes areas generation in Composition

---

packages/atomic-layout-emotion/test/refs.spec.tsx
packages/atomic-layout/src/components/Composition.tsx
packages/atomic-layout/src/components/Only.tsx
packages/atomic-layout/src/components/Visible.tsx
packages/atomic-layout/src/utils/forwardRef.ts
packages/atomic-layout/src/utils/withPlaceholder.tsx
packages/atomic-layout/test/createForwardRefTest.tsx
packages/atomic-layout/test/refs.spec.tsx

- Wraps `Composition`, `Only` and `Visible` in `React.forwardRef()`
- `Box` forwards refs automatically, because it's a styled component
- Closes #297
> It's recommended that the introduction of `forwardRef()` is accompanied by the major version bump. However, since Atomic Layout has not reached the first major version release, these changes won't be released under the major version.

Supports refs forwarding for exported components

---

packages/atomic-layout/src/hooks/useResponsiveValue.ts

The useResponsiveValue hook does not update the value if one of the dependencies changes.
Internationalisation is a good example for this situation.
- Adds a side effect for hook `useResponsiveValue`
- Closes #326

useResponsiveValue: Fires a side effect on dependency change
